on:
    push:
      branches:
        - main
  
        # cd domains/apigrocery.selopia.com/public_html/
        # composer2 update
        # php artisan db:seed --class=ThemeCustomizationSeeder
        # cp .env.example .env
        # sed -i 's/DB_DATABASE=.*/DB_DATABASE=u652464815_sports/g' .env
        # sed -i 's/DB_USERNAME=.*/DB_USERNAME=u652464815_sports/g' .env
        # sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=9;t@^gFkJg/g' .env
        # mkdir -p public/uploads/products/thumbnail
        # mkdir -p public/uploads/products/multiple_image
        # mkdir -p public/uploads/products/featured_banner
        # mkdir -p public/uploads/images/banner
        # mkdir -p public/uploads/images/category
        # mkdir -p public/uploads/images/brands
        # php artisan key:generate
        # php artisan jwt:secret
        # php artisan config:clear
        # php artisan migrate:fresh --seed
        # php artisan optimize
        # php artisan cache:clear
  
name: 🚀 Deploy website on push main
jobs:
    deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
    
        - name: 🚚 Get latest code
          uses: actions/checkout@v2

        - name: 📂 Sync files in client909
          uses: SamKirkland/FTP-Deploy-Action@4.3.0
          with:
            server: nooraa19.com
            username: u100338335.money.qamcl.com
            password: sDe3erf@#^^y231v
            exclude:  |
              **/.git*
              **/.git*/**
              **/public/upload*
              **/public/upload*/**
          continue-on-error: true     
      
        - name: executing remote ssh commands in client909
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: 89.117.139.186
            username: u652464815
            password: sDe3erf@#^^y231v
            port: 65002
            script: |
                 cd domains/money.qamcl.com/public_html/
                 composer2 update
                 cp .env.example .env
                 sed -i 's/DB_DATABASE=.*/DB_DATABASE=u100338335_money/g' .env
                 sed -i 's/DB_USERNAME=.*/DB_USERNAME=u100338335_money/g' .env
                 sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=sthgt:2#M/g' .env
                 php artisan key:generate
                 php artisan config:clear
                 php artisan migrate:fresh --seed
                 php artisan db:seed
                 php artisan optimize
                 php artisan cache:clear
              
          continue-on-error: true  
